CUDNN:
  BENCHMARK: false
  DETERMINISTIC: true
  ENABLED: true
ENV:
  GPUS: (0,)
  OUTPUT_DIR: 'output'
  LOG_DIR: 'log'
  WORKERS: 8
LOGGING:
  PRINT_ITER_FREQ: 2500

DATASET:
  DATASET: ade20k
  ROOT: data/
  TEST_SET: 'list/ade20k/val.lst'
  TRAIN_SET: 'list/ade20k/train.lst'
  NUM_CLASSES: 150
MODEL:
  NAME: BEVANet
  BRANCHES: 2
  CSP_KEEP_RATIO: 0.0
  CSP_CONV_RATIO: 0.0
  LKA: SDLSKA
  DWCONV: DWConv
  PWCONV: PWConv
  PPM: DLKPPM
  FB: BGAF
  SEMANTIC_KERNEL_SIZE: [0, 35, 35]
  DETAIL_KERNEL_SIZE: [0, 23]
  MLP_EXPAND: [4, 4, 4]
  NUM_BLOCKS: [2, 2, 4, 4, 2]
  PLANES: 64
  PPM_PLANES: 96 
  HEAD_PLANES: 128
  NUM_OUTPUTS: 2
  PRETRAINED: ""
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BCE_TYPE: "weight_bce"  # weight_bce, annotator_robust
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 512
  - 512
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 14
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 150
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.0015
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  DETAIL:
    MULTI_SCALE: false
    SMOOTH_KERNEL: 0
    TO_BINARY: true
  FLIP: true
  RAND_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 11
VALID:
  VALID_EPOCH_FREQ: 10
  VALID_LAST_EPOCH: 50
TEST:
  IMAGE_SIZE:
  - 512
  - 512
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 6
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
